using System;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Text;
using global::Avalonia;
using global::Avalonia.Media;
using global::Avalonia.Media.Imaging;
using global::Avalonia.Platform;
using Notepad.Avalonia.Model;

namespace Notepad.Avalonia.Demo;

public class DemoViewModel : INotifyPropertyChanged
{
    public ObservableCollection<ImageEntry> Images { get; } = new();

    private string? _markdownText;
    public string? MarkdownText
    {
        get => _markdownText;
        set { if (_markdownText != value) { _markdownText = value; OnPropertyChanged(); UpdateStatus(); } }
    }

    private string _statusText = "MVVM Demo — edit the note, changes sync with ViewModel.";
    public string StatusText
    {
        get => _statusText;
        set { if (_statusText != value) { _statusText = value; OnPropertyChanged(); } }
    }

    public DemoViewModel()
    {
        var dogBitmap = new Bitmap(
            AssetLoader.Open(
                new Uri("avares://Notepad.Avalonia.Demo/Assets/dog.png")));

        Images.Add(new ImageEntry("dog", dogBitmap));
        Images.Add(new ImageEntry("star", CreateSolidBitmap(Colors.Gold)));
        Images.Add(new ImageEntry("check", CreateSolidBitmap(Colors.LimeGreen)));

        MarkdownText = GenerateGermanPinscherText();
    }

    private static string GenerateGermanPinscherText()
    {
        var sb = new StringBuilder();

        AppendSection(sb, "THE COMPLETE GUIDE TO GERMAN PINSCHERS AND THEIR ADVENTURES",
            "",
            "![dog](dog)",
            "",
            "Welcome to the most comprehensive guide ever written about German Pinschers,",
            "one of the most elegant, intelligent, and adventurous dog breeds in the world.",
            "This guide covers everything from the breed's ancient origins to their modern-day",
            "escapades, training tips, health advice, and the countless adventures they share",
            "with their devoted human companions.",
            "",
            "German Pinschers are medium-sized dogs with a sleek, muscular build that belies",
            "their incredible athleticism and boundless energy. They are known for their",
            "striking appearance, sharp intellect, and a personality that can only be described",
            "as 'larger than life.' Whether they are chasing squirrels in the park, learning",
            "a new trick in record time, or simply lounging on the couch with an air of regal",
            "dignity, German Pinschers never fail to captivate everyone around them.");

        AppendSection(sb, "CHAPTER 1: ORIGINS AND HISTORY",
            "",
            "The German Pinscher is one of the oldest dog breeds originating from Germany.",
            "Their history stretches back to at least the 1400s, when they were valued as",
            "versatile farm dogs capable of ratting, guarding, and companionship. The breed",
            "is considered the progenitor of several other well-known breeds, including the",
            "Miniature Pinscher and the Doberman Pinscher.",
            "",
            "In the early days, German Pinschers roamed the stables and barns of Central",
            "Europe, earning their keep by hunting vermin with ruthless efficiency. A single",
            "German Pinscher could clear an entire barn of rats in a matter of hours, working",
            "tirelessly through the night with a focus and determination that left farmers",
            "in awe of their capabilities.",
            "",
            "The word 'Pinscher' itself is believed to derive from the French word 'pincer,'",
            "meaning to seize or to nip. This is perfectly fitting for a breed that was",
            "originally developed to catch and dispatch vermin with lightning-fast reflexes.",
            "Their ancestors were known as Rattenfanger, or rat catchers, and they took",
            "this job very seriously indeed.",
            "",
            "During the 18th and 19th centuries, the German Pinscher began to be refined",
            "from a rough working dog into a more standardized breed. Breeders selected for",
            "the sleek coat, elegant build, and keen intelligence that we recognize today.",
            "The breed was first officially recognized in Germany in 1879, and a breed",
            "standard was established shortly thereafter.",
            "",
            "However, the German Pinscher's journey was not without its perils. The breed",
            "nearly went extinct after World War II, when breeding programs across Europe",
            "were devastated. By the 1950s, there were almost no German Pinschers left in",
            "existence. It was only through the heroic efforts of Werner Jung, a dedicated",
            "breeder who smuggled oversized Miniature Pinschers from East Germany and used",
            "them along with the last remaining German Pinscher female to rebuild the breed,",
            "that the German Pinscher survived at all.",
            "",
            "This near-extinction event left a lasting mark on the breed. The genetic",
            "bottleneck meant that modern German Pinschers are all descended from a very",
            "small number of founding dogs. Responsible breeders today work carefully to",
            "maintain genetic diversity while preserving the breed's essential characteristics.",
            "",
            "The German Pinscher was recognized by the American Kennel Club in 2003,",
            "relatively late compared to many other breeds. Since then, the breed has slowly",
            "but steadily gained popularity in the United States and around the world,",
            "winning over dog enthusiasts with its striking looks and captivating personality.",
            "",
            "Today, the German Pinscher remains a relatively rare breed. Annual registrations",
            "number in the hundreds rather than the thousands, which means that finding a",
            "well-bred German Pinscher puppy often requires patience and research. But those",
            "who are fortunate enough to share their lives with a German Pinscher will tell",
            "you that the wait is absolutely worth it.");

        AppendSection(sb, "CHAPTER 2: PHYSICAL CHARACTERISTICS",
            "",
            "The German Pinscher is a medium-sized dog that stands between 17 and 20 inches",
            "tall at the shoulder and weighs between 25 and 45 pounds. Despite their moderate",
            "size, they have a commanding presence that makes them seem larger than they are.",
            "",
            "Their coat is one of their most distinctive features. Short, dense, and glossy,",
            "it lies close to the body and requires minimal grooming. The coat comes in",
            "several colors, including solid red (ranging from light fawn to deep stag red),",
            "black and tan, blue and tan, and fawn. The black and tan coloring is perhaps",
            "the most iconic, with rich tan markings on the muzzle, cheeks, above the eyes,",
            "on the chest, legs, and under the tail.",
            "",
            "The head of the German Pinscher is elegant and elongated, with a strong muzzle",
            "that tapers slightly toward the nose. Their eyes are dark and oval-shaped,",
            "giving them an alert, intelligent expression that seems to miss nothing. The",
            "ears are set high and can be either cropped or left natural. When natural, they",
            "fold forward in a V-shape, adding to the breed's expressive appearance.",
            "",
            "The body is well-muscled and compact, with a deep chest that provides ample",
            "lung capacity for sustained activity. The back is short and firm, leading to",
            "a moderately tucked-up abdomen that gives the breed its athletic silhouette.",
            "The legs are straight and strong, built for speed and agility rather than",
            "brute strength.",
            "",
            "One of the most charming physical traits of the German Pinscher is their",
            "movement. They move with a smooth, effortless gait that is a joy to watch.",
            "Whether trotting around the show ring or sprinting across a field, they move",
            "with the grace and precision of a finely tuned athlete.",
            "",
            "The tail was traditionally docked in Germany, but this practice is now banned",
            "in many countries. The natural tail is carried in a gentle curve and adds to",
            "the breed's balanced appearance. Many German Pinscher owners find that the",
            "natural tail is one of the breed's most expressive features, wagging with",
            "enthusiasm when they are happy and tucking slightly when they are uncertain.",
            "",
            "German Pinschers are remarkably clean dogs. They groom themselves almost like",
            "cats, and their short coat repels dirt surprisingly well. A weekly brushing",
            "with a soft bristle brush is usually sufficient to keep their coat in top",
            "condition. Bathing is only necessary occasionally, unless the dog has gotten",
            "into something particularly messy during one of their many adventures.");

        AppendSection(sb, "CHAPTER 3: TEMPERAMENT AND PERSONALITY",
            "",
            "If there is one word that best describes the German Pinscher temperament, it",
            "would be 'spirited.' These dogs approach life with an enthusiasm and intensity",
            "that can be both delightful and challenging. They are never boring, always",
            "thinking, and perpetually ready for the next adventure.",
            "",
            "Intelligence is one of the German Pinscher's defining traits. They are quick",
            "learners who can master complex commands and routines with relatively few",
            "repetitions. However, their intelligence is a double-edged sword. A German",
            "Pinscher who is not given enough mental stimulation will find ways to entertain",
            "themselves, and their ideas of entertainment often involve activities that their",
            "owners would prefer they avoided.",
            "",
            "German Pinschers are known for their problem-solving abilities. They can figure",
            "out how to open gates, doors, and even refrigerators. Many owners have stories",
            "of coming home to find that their German Pinscher has managed to access food",
            "that was supposedly stored in a secure location. These dogs are masters of",
            "observation, watching their owners carefully and learning from what they see.",
            "",
            "Despite their independent streak, German Pinschers are deeply loyal to their",
            "families. They form strong bonds with their owners and can be quite protective.",
            "They are naturally suspicious of strangers and make excellent watchdogs, alerting",
            "their families to any unusual activity with a sharp, authoritative bark.",
            "",
            "With children, German Pinschers can be wonderful companions, provided that both",
            "the dog and the children are properly supervised and educated. They have a",
            "playful nature that meshes well with active children, but their high energy",
            "and sometimes boisterous play style means they are generally better suited to",
            "families with older children who understand how to interact respectfully with",
            "dogs.",
            "",
            "One of the most endearing traits of the German Pinscher is their sense of",
            "humor. These dogs genuinely seem to enjoy making their owners laugh. They have",
            "a repertoire of silly behaviors, from 'talking' with various vocalizations to",
            "performing impromptu acrobatic feats. Many German Pinscher owners report that",
            "their dogs seem to understand when they have done something funny and will",
            "repeat the behavior to get a laugh.",
            "",
            "However, the German Pinscher's strong personality means they are not a breed",
            "for everyone. They need an owner who can provide firm, consistent leadership",
            "without being harsh or authoritarian. A German Pinscher who does not respect",
            "their owner's authority can become willful and difficult to manage. But with",
            "the right owner, a German Pinscher is a devoted, entertaining, and endlessly",
            "fascinating companion.");

        AppendSection(sb, "CHAPTER 4: THE MORNING ADVENTURE",
            "",
            "Every day with a German Pinscher begins with an adventure. The moment the alarm",
            "goes off, the German Pinscher is already awake, standing at the bedside with",
            "their tail wagging and eyes bright with anticipation. There is no such thing",
            "as sleeping in when you share your home with a German Pinscher.",
            "",
            "The morning walk is a sacred ritual. A German Pinscher does not simply walk;",
            "they patrol. Every bush must be investigated, every interesting scent must be",
            "catalogued, and every squirrel must be pursued with single-minded determination.",
            "The morning walk is not just exercise; it is a full sensory experience that",
            "engages every fiber of the German Pinscher's being.",
            "",
            "Consider the case of Fritz, a three-year-old German Pinscher who lives in a",
            "quiet suburban neighborhood. Fritz's morning routine begins at precisely 6:15 AM,",
            "when he leaps onto his owner's bed with the grace of a gazelle and the weight",
            "of a small boulder. After a brief session of face-licking and tail-wagging,",
            "Fritz leads his owner to the front door, where the leash is waiting.",
            "",
            "![dog](dog)",
            "",
            "Once outside, Fritz transforms into a detective. His nose goes to the ground,",
            "and he methodically checks every tree, fire hydrant, and fence post in the",
            "neighborhood. He knows the scent signature of every dog within a three-block",
            "radius and can tell within seconds whether any new dogs have passed through",
            "his territory overnight.",
            "",
            "But Fritz's morning adventure is not complete without a proper chase. The",
            "neighborhood is home to several bold squirrels who have learned to taunt Fritz",
            "from the safety of their trees. Fritz responds to each sighting with a burst",
            "of speed that would impress an Olympic sprinter, racing across lawns and",
            "around obstacles with breathtaking agility. He never catches the squirrels,",
            "of course, but the thrill of the chase is what matters.",
            "",
            "After approximately 45 minutes of walking, sniffing, and squirrel-chasing,",
            "Fritz returns home with the satisfied air of a job well done. He drinks deeply",
            "from his water bowl, stretches luxuriously on his favorite spot on the couch,",
            "and settles in for a well-deserved nap. But even in sleep, his paws twitch",
            "and his nose quivers, suggesting that in his dreams, the adventure continues.");

        AppendSection(sb, "CHAPTER 5: TRAINING AND EDUCATION",
            "",
            "Training a German Pinscher is an exercise in patience, creativity, and mutual",
            "respect. These dogs are incredibly intelligent, but they are also strong-willed",
            "and can be surprisingly stubborn when they decide they do not want to do",
            "something. The key to successful training is making the German Pinscher believe",
            "that whatever you want them to do was actually their idea in the first place.",
            "",
            "Positive reinforcement is the most effective training method for German Pinschers.",
            "They respond enthusiastically to treats, praise, and play. Harsh corrections",
            "or punishment-based methods will backfire spectacularly with this breed. A German",
            "Pinscher who feels they are being treated unfairly will shut down completely,",
            "refusing to cooperate and possibly developing behavioral problems.",
            "",
            "Socialization is absolutely critical for German Pinschers. Because of their",
            "naturally suspicious nature toward strangers, early and extensive socialization",
            "is necessary to ensure they grow into well-adjusted adults. This means exposing",
            "them to a wide variety of people, places, sounds, and experiences during their",
            "first few months of life.",
            "",
            "Puppy classes are an excellent starting point. A good puppy class provides",
            "controlled socialization opportunities as well as basic obedience training. It",
            "also gives German Pinscher puppies a chance to learn appropriate play behavior",
            "with other dogs, which is important for a breed that can sometimes be bossy",
            "with other canines.",
            "",
            "Basic obedience commands like sit, down, stay, come, and heel should be taught",
            "early and practiced regularly. German Pinschers learn these commands quickly",
            "but may test their owners by pretending they have never heard the command before.",
            "Consistency is key. Every time a command is given, it must be followed through.",
            "If a German Pinscher learns that they can ignore a command sometimes, they will",
            "try to ignore it every time.",
            "",
            "Many German Pinschers excel in advanced training activities such as agility,",
            "obedience competition, rally, and tracking. These activities provide the mental",
            "and physical stimulation that the breed craves while strengthening the bond",
            "between dog and owner. A German Pinscher competing in agility is a sight to",
            "behold, weaving through poles and launching over jumps with speed and precision.",
            "",
            "House training is generally straightforward with German Pinschers, as they are",
            "naturally clean dogs who prefer to keep their living space tidy. Crate training",
            "is recommended, as it gives the puppy a safe den to retreat to and prevents",
            "destructive behavior when the owner is away. Most German Pinschers take to",
            "crate training quickly, especially if the crate is associated with positive",
            "experiences like treats and comfortable bedding.",
            "",
            "One area of training that requires special attention is impulse control. German",
            "Pinschers have strong prey drive and can become easily excited. Teaching them",
            "to control their impulses, whether it is waiting patiently for food, not jumping",
            "on guests, or resisting the urge to chase every moving object, is essential for",
            "living harmoniously with this energetic breed.");

        AppendSection(sb, "CHAPTER 6: THE GREAT SQUIRREL PURSUIT",
            "",
            "No discussion of German Pinscher adventures would be complete without addressing",
            "the legendary rivalry between German Pinschers and squirrels. This is a conflict",
            "that has raged for centuries, spanning continents and generations of both species.",
            "",
            "![dog](dog)",
            "",
            "The squirrel represents everything that triggers a German Pinscher's prey drive:",
            "it is small, fast, erratic in its movements, and seemingly designed to provoke",
            "a chase. When a German Pinscher spots a squirrel, everything else ceases to",
            "exist. Commands, treats, other dogs, even their beloved owners become invisible",
            "as the German Pinscher locks onto their quarry with laser-like focus.",
            "",
            "The typical squirrel encounter follows a predictable pattern. First, the German",
            "Pinscher freezes, every muscle tense, eyes fixed on the squirrel. Then comes",
            "a moment of stillness so perfect that the dog seems to become a statue. Finally,",
            "like a coiled spring released, the German Pinscher explodes into motion, covering",
            "the distance between themselves and the squirrel in a blur of speed.",
            "",
            "The squirrel, for its part, usually waits until the last possible moment before",
            "scampering up the nearest tree. There, perched safely on a branch just out of",
            "reach, it chatters angrily at the German Pinscher below. The German Pinscher",
            "responds by circling the tree, standing on their hind legs, and occasionally",
            "attempting to climb the trunk. This standoff can last anywhere from five minutes",
            "to the better part of an hour.",
            "",
            "Some German Pinschers have developed increasingly sophisticated strategies for",
            "squirrel hunting. There are reports of German Pinschers who have learned to",
            "approach squirrels from downwind, using hedges and parked cars as cover. Others",
            "have figured out that squirrels tend to use the same routes between trees and",
            "will position themselves along these routes in ambush.",
            "",
            "Despite their best efforts, German Pinschers rarely actually catch squirrels.",
            "This seems to matter very little to the dogs, who appear to enjoy the chase",
            "itself far more than any potential catch. The squirrel pursuit is not about",
            "the destination; it is about the journey.");

        AppendSection(sb, "CHAPTER 7: HEALTH AND WELLNESS",
            "",
            "German Pinschers are generally healthy dogs with a lifespan of 12 to 14 years.",
            "However, like all breeds, they are prone to certain health conditions that",
            "potential owners should be aware of.",
            "",
            "Hip dysplasia, while less common in German Pinschers than in larger breeds,",
            "can still occur. Responsible breeders will have their breeding stock evaluated",
            "by the Orthopedic Foundation for Animals (OFA) to reduce the incidence of this",
            "condition. Puppies from health-tested parents are much less likely to develop",
            "hip problems later in life.",
            "",
            "Eye conditions, including cataracts and progressive retinal atrophy (PRA), have",
            "been documented in the breed. Annual eye examinations by a veterinary",
            "ophthalmologist are recommended to catch any problems early. Genetic testing",
            "for PRA is available and should be performed on all breeding dogs.",
            "",
            "Von Willebrand's disease, a blood clotting disorder, has been identified in",
            "some German Pinscher lines. This condition can cause excessive bleeding after",
            "injury or surgery. DNA testing can identify carriers, and responsible breeders",
            "will not breed two carriers together.",
            "",
            "Heart conditions, particularly dilated cardiomyopathy, can occur in the breed.",
            "Regular veterinary check-ups that include cardiac evaluation are important for",
            "early detection and management of any heart issues.",
            "",
            "Maintaining a healthy weight is crucial for German Pinschers. These dogs are",
            "natural athletes, and excess weight can put undue stress on their joints and",
            "organs. A high-quality diet formulated for active medium-sized dogs, combined",
            "with regular exercise, will help keep a German Pinscher in optimal condition.",
            "",
            "Exercise needs for a German Pinscher are substantial. They require at least",
            "one to two hours of vigorous exercise daily. This can include walks, runs,",
            "hiking, swimming, and play sessions. Mental exercise is equally important and",
            "can be provided through training sessions, puzzle toys, and interactive games.",
            "",
            "Dental care is often overlooked but is an important aspect of German Pinscher",
            "health. Regular tooth brushing, dental chews, and professional dental cleanings",
            "as recommended by a veterinarian will help prevent dental disease, which can",
            "lead to more serious health problems if left untreated.");

        AppendSection(sb, "CHAPTER 8: THE PARK ADVENTURES",
            "",
            "The dog park is the German Pinscher's kingdom. Here, they can run, play, and",
            "socialize to their heart's content. But a trip to the dog park with a German",
            "Pinscher is never a simple affair; it is an event filled with drama, comedy,",
            "and occasionally, a touch of chaos.",
            "",
            "When a German Pinscher arrives at the dog park, they make an entrance. There",
            "is nothing subtle about their arrival. They burst through the gate with an",
            "energy that sends smaller dogs scattering and larger dogs pausing to take",
            "notice. The German Pinscher then proceeds to perform a lap of the entire park",
            "at top speed, ears pinned back and legs churning, as if to announce to all",
            "present that the real entertainment has arrived.",
            "",
            "German Pinschers have a unique play style that can sometimes be misunderstood",
            "by other dogs and their owners. They play rough, with lots of body-slamming,",
            "wrestling, and dramatic vocalizations. They also have a tendency to herd other",
            "dogs, nipping at their heels and attempting to control their movements. This",
            "behavior is a remnant of their herding instincts and is not aggressive, but",
            "it can annoy dogs who prefer a calmer play style.",
            "",
            "One of the German Pinscher's favorite park activities is the game of keep-away.",
            "They will find a stick, ball, or other toy and parade around the park with it,",
            "inviting other dogs to chase them. When another dog gets close, the German",
            "Pinscher accelerates away with a burst of speed, leaving their pursuer in the",
            "dust. This game can continue for an impressively long time, as the German",
            "Pinscher's stamina is legendary.",
            "",
            "Water features at dog parks present a special opportunity for German Pinscher",
            "adventures. While not all German Pinschers are natural swimmers, many develop",
            "a love of water once they are introduced to it gradually. A German Pinscher",
            "playing in a splash pad or wading pool is a picture of pure joy, splashing",
            "with abandon and attempting to bite the water streams.",
            "",
            "The return home from the dog park is invariably followed by what German Pinscher",
            "owners call 'the zoomies.' This is a period of frantic, seemingly random running",
            "that occurs despite the fact that the dog has just spent an hour or more engaged",
            "in vigorous exercise. The zoomies typically last five to ten minutes and end as",
            "suddenly as they begin, with the German Pinscher collapsing into a deep sleep.");

        AppendSection(sb, "CHAPTER 9: LIVING WITH A GERMAN PINSCHER",
            "",
            "Sharing your home with a German Pinscher is an experience that will transform",
            "your daily life in ways both wonderful and unexpected. These dogs have a way",
            "of becoming the center of their family's universe, and most German Pinscher",
            "owners would not have it any other way.",
            "",
            "German Pinschers are house dogs through and through. They should never be kept",
            "in outdoor kennels or left in the yard for extended periods. They crave human",
            "companionship and will become destructive and unhappy if left alone too much.",
            "Separation anxiety can be an issue with this breed, particularly if they are",
            "not gradually accustomed to being alone.",
            "",
            "The ideal living situation for a German Pinscher includes a securely fenced yard",
            "for off-leash play and exploration. The fence should be at least five feet high,",
            "as German Pinschers are impressive jumpers. Some owners have found that their",
            "German Pinschers can clear a four-foot fence with ease, leading to unexpected",
            "neighborhood adventures that are more stressful for the owner than the dog.",
            "",
            "Inside the home, German Pinschers are surprisingly well-behaved once they are",
            "past the puppy stage. They are clean dogs who rarely have accidents and tend",
            "to keep their living space tidy. However, they do have a fondness for soft",
            "surfaces and will claim the most comfortable spot in the house as their own,",
            "whether that is the center of the sofa, the best armchair, or the middle of",
            "the bed.",
            "",
            "Counter-surfing is a common German Pinscher behavior that owners must address",
            "early. These dogs are tall enough to reach kitchen counters and smart enough",
            "to know that counters often contain interesting things. Many a German Pinscher",
            "owner has learned the hard way to never leave food unattended on any surface",
            "within the dog's considerable reach.",
            "",
            "German Pinschers get along well with other dogs when properly socialized, but",
            "they can be dominant and may not do well with dogs of the same sex. Introducing",
            "a German Pinscher to a household with existing pets should be done carefully",
            "and gradually. Cats can coexist with German Pinschers, but the dog's prey drive",
            "means that small pets like hamsters, birds, and rabbits may not be safe.",
            "",
            "The German Pinscher's vocal nature is something that potential owners should",
            "consider. They are alert dogs who will bark at anything unusual, and their",
            "bark is surprisingly loud for their size. While this makes them excellent",
            "watchdogs, it can be a source of friction with neighbors in apartment or",
            "townhouse settings. Training can help manage excessive barking, but it is",
            "unlikely to eliminate it entirely.");

        AppendSection(sb, "CHAPTER 10: THE MIDNIGHT PATROL",
            "",
            "Even at night, the German Pinscher's adventurous spirit does not rest. Many",
            "owners report that their German Pinschers conduct regular nighttime patrols,",
            "checking windows, doors, and the perimeter of the house to ensure that all",
            "is secure.",
            "",
            "The midnight patrol typically begins with the German Pinscher silently rising",
            "from their sleeping spot and padding softly through the house. They check each",
            "room methodically, pausing to listen at windows and sniff at doors. If anything",
            "seems amiss, they may emit a low growl or a single sharp bark to alert their",
            "sleeping family.",
            "",
            "Some German Pinschers take their nighttime duties so seriously that they develop",
            "regular patrol routes, visiting the same spots at approximately the same times",
            "each night. Owners who have set up cameras have been amazed to see their dogs",
            "moving through the house with the precision and purpose of a security guard.",
            "",
            "Nocturnal sounds that would go unnoticed by most dogs are immediately flagged",
            "by the German Pinscher's keen ears. A raccoon on the porch, a cat in the yard,",
            "or even the distant sound of a car door closing several houses away can trigger",
            "a response from the vigilant German Pinscher.",
            "",
            "While this vigilance is admirable and makes the German Pinscher an outstanding",
            "household guardian, it can occasionally be disruptive to sleep. Owners learn to",
            "distinguish between their dog's 'genuine alert' bark and their 'I heard a leaf",
            "fall three blocks away' bark, and to respond accordingly.");

        AppendSection(sb, "CHAPTER 11: NUTRITION AND DIET",
            "",
            "Feeding a German Pinscher requires attention to quality, quantity, and timing.",
            "These active dogs have high metabolic rates and need a diet that provides the",
            "energy they require without leading to excess weight gain.",
            "",
            "A high-quality commercial dog food formulated for active medium-sized breeds",
            "is a good foundation. Look for foods that list a named meat protein (such as",
            "chicken, beef, or fish) as the first ingredient. Avoid foods that rely heavily",
            "on fillers like corn, wheat, and soy, which provide calories but little",
            "nutritional value.",
            "",
            "Many German Pinscher owners supplement their dog's commercial diet with fresh",
            "foods such as lean meats, fish, eggs, and vegetables. These additions can",
            "provide variety and additional nutrients. However, any dietary changes should",
            "be made gradually to avoid digestive upset.",
            "",
            "The amount of food a German Pinscher needs depends on their age, weight,",
            "activity level, and individual metabolism. Most adult German Pinschers do well",
            "on two meals per day, with the total daily amount ranging from one and a half",
            "to two and a half cups of dry food. Puppies need more frequent feeding, with",
            "three to four meals per day until they are about six months old.",
            "",
            "Treats should be used judiciously. While treats are an excellent training tool,",
            "they can quickly add up in calories. Healthy treat options include small pieces",
            "of cooked chicken or turkey, baby carrots, apple slices (without seeds), and",
            "blueberries. These provide a tasty reward without the empty calories of many",
            "commercial treats.",
            "",
            "Fresh water should always be available, especially after exercise. German",
            "Pinschers can be picky about their water, preferring fresh, clean water over",
            "water that has been sitting in the bowl for a while. Some owners find that",
            "their German Pinschers prefer running water and invest in a pet water fountain.",
            "",
            "Foods that should never be given to a German Pinscher (or any dog) include",
            "chocolate, grapes, raisins, onions, garlic, xylitol (an artificial sweetener),",
            "macadamia nuts, and cooked bones. These foods can be toxic or dangerous and",
            "should be kept well out of the German Pinscher's impressive reach.");

        AppendSection(sb, "CHAPTER 12: GROOMING AND CARE",
            "",
            "One of the many advantages of the German Pinscher is their low-maintenance",
            "coat. Their short, dense fur requires minimal grooming compared to many other",
            "breeds. However, 'minimal' does not mean 'none,' and a regular grooming routine",
            "will keep your German Pinscher looking and feeling their best.",
            "",
            "Weekly brushing with a soft bristle brush or rubber grooming mitt will remove",
            "loose hair and distribute natural oils throughout the coat, keeping it shiny",
            "and healthy. During shedding season (spring and fall), more frequent brushing",
            "may be needed to manage the increased hair loss.",
            "",
            "Bathing should be done only as needed, typically every four to six weeks or",
            "when the dog gets particularly dirty. Over-bathing can strip the coat of its",
            "natural oils, leading to dry, dull fur and irritated skin. When bathing, use a",
            "mild dog shampoo and rinse thoroughly to remove all soap residue.",
            "",
            "Nail care is important and often overlooked. German Pinscher nails should be",
            "trimmed every two to three weeks. If you can hear the nails clicking on the",
            "floor, they are too long. Long nails can cause discomfort and affect the dog's",
            "gait. Many German Pinschers dislike having their nails trimmed, so it is",
            "important to accustom them to the process from a young age.",
            "",
            "Ear cleaning should be done weekly, especially if the ears are natural (uncropped).",
            "Natural ears fold over, creating a warm, moist environment that can be conducive",
            "to ear infections. Use a veterinarian-recommended ear cleaner and a cotton ball",
            "to gently wipe the outer ear canal. Never insert anything into the ear canal.",
            "",
            "Dental hygiene is crucial. Daily tooth brushing with a dog-specific toothpaste",
            "is ideal, but even two to three times per week can significantly reduce the risk",
            "of dental disease. Dental chews and toys can supplement brushing but should not",
            "replace it entirely.");

        AppendSection(sb, "CHAPTER 13: THE BEACH EXPEDITION",
            "",
            "Taking a German Pinscher to the beach is an adventure that deserves its own",
            "chapter. The combination of sand, water, seabirds, and wide-open spaces creates",
            "an environment that brings out every aspect of the German Pinscher's personality.",
            "",
            "![dog](dog)",
            "",
            "Upon arriving at the beach, the German Pinscher's first instinct is to run.",
            "The vast expanse of sand provides an irresistible runway, and the German Pinscher",
            "will sprint back and forth along the shoreline with a speed that draws admiring",
            "glances from other beachgoers. This initial burst of energy can last ten to",
            "fifteen minutes, during which the dog covers an astonishing amount of ground.",
            "",
            "The waves present a fascinating and somewhat perplexing challenge. Many German",
            "Pinschers are initially suspicious of the ocean, approaching the water's edge",
            "cautiously and then leaping backward when a wave rushes toward them. Over time,",
            "most German Pinschers learn to enjoy the water, romping through the shallows",
            "and occasionally venturing into deeper water for a swim.",
            "",
            "Seagulls are the beach equivalent of squirrels, and the German Pinscher's",
            "reaction to them is predictably intense. A flock of seagulls standing on the",
            "beach is simply too much temptation for any self-respecting German Pinscher.",
            "The resulting charge scatters the birds into the air, where they wheel and",
            "cry while the German Pinscher watches with satisfaction, tail wagging furiously.",
            "",
            "Digging in the sand is another beloved beach activity. German Pinschers can",
            "dig with remarkable speed and enthusiasm, sending sand flying in all directions.",
            "Left to their own devices, they will excavate holes of impressive depth, often",
            "startling their owners with the speed at which they can modify the landscape.",
            "",
            "After a day at the beach, the German Pinscher requires a thorough rinse to",
            "remove salt and sand from their coat. The car ride home is typically very quiet,",
            "with the exhausted dog sleeping soundly in the back seat, dreaming of waves,",
            "seagulls, and the next beach expedition.");

        AppendSection(sb, "CHAPTER 14: GERMAN PINSCHERS AND OTHER PETS",
            "",
            "The relationship between German Pinschers and other household pets is a topic",
            "that generates much discussion among breed enthusiasts. The German Pinscher's",
            "strong prey drive and dominant personality can make multi-pet households",
            "challenging but not impossible.",
            "",
            "With other dogs, German Pinschers generally do best with dogs of the opposite",
            "sex and similar energy level. Two German Pinschers of the same sex can sometimes",
            "develop rivalry that escalates into conflict. If you plan to have multiple dogs,",
            "careful introduction and ongoing management are essential.",
            "",
            "Cats are a more complicated matter. A German Pinscher raised with cats from",
            "puppyhood can learn to accept feline housemates, but the prey drive never truly",
            "disappears. Many German Pinscher and cat households operate on a system of",
            "mutual respect: the cat maintains high ground and the dog learns that chasing",
            "the cat results in swift and painful retribution from sharp feline claws.",
            "",
            "Small pets such as hamsters, guinea pigs, rabbits, and birds should be kept",
            "securely away from German Pinschers at all times. No amount of training will",
            "reliably override the breed's instinct to pursue and catch small, fast-moving",
            "creatures. This is not a flaw in the breed; it is the very trait that made",
            "them invaluable as ratting dogs for centuries.",
            "",
            "Fish tanks, interestingly, can provide endless entertainment for German",
            "Pinschers who discover them. The movement of fish triggers the dog's prey",
            "drive but the barrier of glass prevents any actual pursuit. Some German",
            "Pinschers will sit in front of an aquarium for extended periods, watching",
            "the fish with focused intensity.");

        AppendSection(sb, "CHAPTER 15: THE HIKING COMPANION",
            "",
            "German Pinschers make exceptional hiking companions. Their stamina, agility,",
            "and love of the outdoors make them natural partners for trail adventures of",
            "all levels, from easy nature walks to challenging mountain hikes.",
            "",
            "![dog](dog)",
            "",
            "On the trail, the German Pinscher is in their element. Every rustle in the",
            "underbrush is investigated, every new scent is catalogued, and every vista",
            "is appreciated. They move confidently over varied terrain, their sure-footed",
            "nature allowing them to navigate rocky paths, fallen logs, and stream crossings",
            "with ease.",
            "",
            "Proper preparation is essential for hiking with a German Pinscher. They need",
            "plenty of water, especially in warm weather, as their short coat offers less",
            "insulation against heat than longer-coated breeds. A collapsible water bowl",
            "and enough water for both dog and human are must-have items.",
            "",
            "Paw protection may be necessary on particularly rough or hot terrain. While",
            "German Pinschers have tough pads, prolonged hiking on sharp rocks or hot",
            "surfaces can cause injury. Dog boots or paw wax can provide protection.",
            "",
            "Wildlife encounters are always a possibility on the trail, and the German",
            "Pinscher's prey drive must be managed carefully. A sturdy leash and reliable",
            "recall command are non-negotiable. Encounters with deer, rabbits, or birds",
            "can trigger an intense chase response that may lead the dog far from the trail.",
            "",
            "After a long hike, the German Pinscher may seem inexhaustible, bouncing around",
            "the campsite or the car with seemingly undiminished energy. This is deceptive.",
            "Once the adrenaline wears off, the dog will sleep deeply and may even be a",
            "little stiff the next day. Older German Pinschers in particular may benefit",
            "from a rest day after an especially strenuous hike.",
            "",
            "Hiking with a German Pinscher creates memories that last a lifetime. There is",
            "something deeply satisfying about sharing the trail with a companion who",
            "approaches every step with enthusiasm and every new discovery with wonder.");

        AppendSection(sb, "CHAPTER 16: FAMOUS GERMAN PINSCHERS IN HISTORY",
            "",
            "While the German Pinscher has never achieved the widespread fame of breeds like",
            "the Labrador Retriever or German Shepherd, the breed has had its share of",
            "notable representatives throughout history.",
            "",
            "Perhaps the most important German Pinscher in history was Kitti von Bodestrand,",
            "the female who, along with several oversized Miniature Pinschers, was used by",
            "Werner Jung to rebuild the breed after World War II. Without Kitti, the German",
            "Pinscher would almost certainly have gone extinct. Her descendants can be found",
            "in the pedigrees of virtually every German Pinscher alive today.",
            "",
            "In the show ring, German Pinschers have been making increasingly strong",
            "showings at prestigious events around the world. The breed has won Best in",
            "Group at several major shows and continues to gain recognition for its",
            "striking appearance and sound structure.",
            "",
            "German Pinschers have also found success in various dog sports. Their speed",
            "and agility make them formidable competitors in agility trials, while their",
            "intelligence and trainability shine in obedience and rally competitions.",
            "Several German Pinschers have earned advanced titles in multiple disciplines,",
            "demonstrating the breed's versatility.",
            "",
            "In popular culture, the German Pinscher remains somewhat under the radar.",
            "Unlike their cousin the Doberman, who has appeared in countless movies and",
            "television shows, the German Pinscher has yet to have its Hollywood moment.",
            "Breed enthusiasts are divided on whether this is a good thing or not. Some",
            "worry that increased popularity could lead to irresponsible breeding, while",
            "others believe that greater visibility would help more people discover this",
            "wonderful breed.");

        AppendSection(sb, "CHAPTER 17: SEASONAL ADVENTURES",
            "",
            "German Pinschers experience each season differently, and their adventures",
            "change with the weather in entertaining and sometimes challenging ways.",
            "",
            "Spring brings renewed energy and a burst of shedding. The German Pinscher",
            "greets the warmer weather with enthusiasm, eager to spend more time outdoors",
            "after the confinement of winter. Spring also brings baby animals, which can",
            "trigger the German Pinscher's prey drive. Baby rabbits in the yard, fledgling",
            "birds on the ground, and newly emerged chipmunks all present irresistible",
            "temptations.",
            "",
            "Summer is the season of maximum adventure. Long days mean more time for walks,",
            "hikes, and outdoor play. However, German Pinschers must be protected from",
            "overheating. Their short coat provides minimal insulation, and their dark",
            "coloring (particularly in black and tan dogs) can absorb a lot of heat. Early",
            "morning and evening exercise is best during the hottest months, with access",
            "to shade and water at all times.",
            "",
            "Autumn is perhaps the German Pinscher's favorite season. The cooler temperatures",
            "are ideal for vigorous exercise, and the falling leaves provide an endless",
            "source of entertainment. Many German Pinschers develop a game of chasing and",
            "pouncing on falling leaves, displaying the same intensity they would show in",
            "pursuing actual prey. Leaf piles are irresistible; a German Pinscher will",
            "launch themselves into a carefully raked leaf pile with gleeful abandon.",
            "",
            "Winter presents the most significant challenges. German Pinschers have minimal",
            "body fat and a thin coat, making them poorly suited to cold weather. A warm",
            "dog coat or sweater is essential for winter walks, and outdoor time should be",
            "limited in extremely cold conditions. Many German Pinschers will refuse to go",
            "outside in rain or snow, standing at the door and giving their owner a look",
            "of pure disbelief that anyone would expect them to venture into such conditions.",
            "",
            "Despite their cold sensitivity, some German Pinschers do learn to enjoy snow.",
            "The novelty of a white landscape and the excitement of plunging through drifts",
            "can overcome their natural aversion to cold. These dogs will romp through the",
            "snow with enthusiasm, though they typically want to come inside much sooner",
            "than cold-weather breeds.");

        AppendSection(sb, "CHAPTER 18: THE GERMAN PINSCHER COMMUNITY",
            "",
            "Owning a German Pinscher automatically grants you membership in a passionate",
            "and close-knit community of breed enthusiasts. This community spans the globe",
            "and is connected through breed clubs, social media groups, dog shows, and",
            "shared experiences.",
            "",
            "The German Pinscher Club of America (GPCA) is the primary breed club in the",
            "United States. It serves as a resource for breed information, breeder referrals,",
            "and health data. The club also organizes the annual National Specialty show,",
            "which brings together German Pinscher enthusiasts from across the country for",
            "a celebration of the breed.",
            "",
            "Online communities dedicated to German Pinschers are vibrant and active. Facebook",
            "groups, Reddit communities, and breed-specific forums provide spaces where owners",
            "can share stories, seek advice, and celebrate the unique joys and challenges of",
            "life with a German Pinscher. These communities are invaluable for new owners",
            "who may be experiencing the breed's quirks for the first time.",
            "",
            "German Pinscher meetups and playdates are popular events that allow dogs and",
            "their owners to socialize. Watching a group of German Pinschers play together",
            "is an unforgettable experience. The speed, agility, and intensity of their play",
            "is breathtaking, and the bonds between the dogs form quickly and strongly.",
            "",
            "The German Pinscher community is also deeply committed to breed health and",
            "welfare. Breed-specific rescue organizations work to find homes for German",
            "Pinschers who need them, whether they are surrendered by owners who are unable",
            "to meet the breed's needs or rescued from less-than-ideal situations. These",
            "organizations provide an important safety net for the breed.");

        AppendSection(sb, "CHAPTER 19: BREEDING AND PUPPIES",
            "",
            "Breeding German Pinschers is a serious undertaking that should only be pursued",
            "by experienced breeders with a deep understanding of the breed's health,",
            "temperament, and structure. The breed's small gene pool makes responsible",
            "breeding decisions especially important.",
            "",
            "A responsible German Pinscher breeder will perform comprehensive health testing",
            "on all breeding dogs, including hip evaluations, eye examinations, cardiac",
            "screening, and DNA testing for known genetic conditions. They will carefully",
            "select breeding pairs based on complementary strengths and will be transparent",
            "about any health issues in their lines.",
            "",
            "German Pinscher litters are typically small, averaging three to six puppies.",
            "The puppies are born with their eyes and ears closed and are completely",
            "dependent on their mother for the first few weeks of life. They develop",
            "quickly, opening their eyes at about two weeks and beginning to walk and",
            "explore their environment by three weeks.",
            "",
            "The socialization period from three to twelve weeks is critical for German",
            "Pinscher puppies. Good breeders begin socialization early, exposing puppies",
            "to a variety of people, sounds, surfaces, and experiences. This early",
            "socialization lays the foundation for a confident, well-adjusted adult dog.",
            "",
            "German Pinscher puppies are adorable but demanding. They are bundles of energy",
            "who require constant supervision, consistent training, and patient guidance.",
            "Puppy-proofing the home is essential, as these curious and determined puppies",
            "will investigate everything within reach and many things that should not be.",
            "",
            "Most reputable breeders will not release puppies to their new homes until they",
            "are at least eight to ten weeks old. During this time, the puppies learn crucial",
            "social skills from their mother and littermates that will serve them well",
            "throughout their lives.");

        AppendSection(sb, "CHAPTER 20: TRAVELING WITH A GERMAN PINSCHER",
            "",
            "German Pinschers are generally good travel companions, provided they are",
            "properly acclimated to the experience. Their moderate size makes them more",
            "manageable than larger breeds, and their adaptable nature allows them to adjust",
            "to new environments relatively quickly.",
            "",
            "Car travel is the most common form of transportation for dogs. German Pinschers",
            "should always be secured in the car, either in a crate or with a dog-specific",
            "seat belt. Most German Pinschers learn to enjoy car rides and will eagerly jump",
            "into the car at the mere jingle of keys.",
            "",
            "For longer road trips, plan regular stops for bathroom breaks, water, and",
            "exercise. German Pinschers need to stretch their legs and burn off energy,",
            "so look for rest stops with grassy areas where the dog can walk and play.",
            "Never leave a German Pinscher in a parked car, especially in warm weather.",
            "The interior of a car can reach dangerous temperatures in a matter of minutes.",
            "",
            "Air travel with a German Pinscher is possible but requires advance planning.",
            "Due to their size, most German Pinschers will need to travel in the cargo hold",
            "rather than in the cabin. This can be stressful for both dog and owner, so",
            "careful consideration should be given to whether air travel is truly necessary.",
            "",
            "Hotels and vacation rentals that accept pets are increasingly common, but it",
            "is always wise to confirm the pet policy before booking. Bring your German",
            "Pinscher's familiar bedding, toys, and food to help them feel comfortable",
            "in unfamiliar surroundings.",
            "",
            "Camping with a German Pinscher is an absolute joy. The combination of outdoor",
            "living, new smells, and constant adventure makes camping the ideal vacation for",
            "a German Pinscher and their owner. Just be prepared for the dog to alert you",
            "to every nocturnal visitor to the campsite, from raccoons to deer to fellow",
            "campers walking past on their way to the facilities.");

        AppendSection(sb, "CHAPTER 21: AGING GRACEFULLY",
            "",
            "German Pinschers age with the same dignity and spirit that characterizes them",
            "throughout their lives. While they may slow down physically, their personality",
            "remains vibrant and engaged well into their senior years.",
            "",
            "The senior years for a German Pinscher typically begin around eight to ten",
            "years of age. Changes may be gradual: a slight graying of the muzzle, a",
            "preference for shorter walks, more time spent napping in sunny spots. But",
            "the spark in their eyes and the enthusiasm for their favorite activities",
            "remain unchanged.",
            "",
            "Veterinary care becomes even more important for senior German Pinschers.",
            "Semi-annual check-ups, including blood work and dental evaluations, can help",
            "catch age-related health issues early. Arthritis, dental disease, and organ",
            "changes are common in older dogs and are best managed when detected early.",
            "",
            "Diet adjustments may be necessary for the senior German Pinscher. A food",
            "formulated for senior dogs or one with reduced calories can help prevent",
            "weight gain as activity levels decrease. Joint supplements such as glucosamine",
            "and chondroitin may help maintain mobility and comfort.",
            "",
            "Exercise for senior German Pinschers should be adjusted to their comfort level.",
            "Shorter, more frequent walks are often better than long, strenuous outings.",
            "Swimming is an excellent low-impact exercise that many senior dogs enjoy.",
            "Mental exercise remains important and can be provided through puzzle toys,",
            "scent games, and gentle training sessions.",
            "",
            "The bond between a German Pinscher and their owner only deepens with age.",
            "There is a special tenderness in the relationship between a person and their",
            "aging dog, a mutual understanding born of years of shared adventures. The",
            "senior German Pinscher may no longer be able to chase squirrels at full speed",
            "or hike for hours on end, but the love and loyalty they offer is, if anything,",
            "even more profound than before.",
            "",
            "Saying goodbye to a beloved German Pinscher is one of the hardest things any",
            "dog owner will face. The grief is real and should be honored. But in time,",
            "the pain softens and what remains are the memories: the adventures shared,",
            "the laughter inspired, the unconditional love given. And for many, the healing",
            "comes when they open their heart and home to another German Pinscher, beginning",
            "a new chapter of adventures.");

        AppendSection(sb, "CHAPTER 22: GERMAN PINSCHER MYTHS AND MISCONCEPTIONS",
            "",
            "Several myths and misconceptions surround the German Pinscher breed. Addressing",
            "these can help potential owners make informed decisions and prevent unrealistic",
            "expectations.",
            "",
            "Myth: German Pinschers are miniature Dobermans.",
            "Reality: While the German Pinscher contributed to the development of the",
            "Doberman, they are a distinct and separate breed with their own unique",
            "characteristics. German Pinschers are smaller, have a different temperament,",
            "and have a much longer breed history than the Doberman.",
            "",
            "Myth: German Pinschers are aggressive.",
            "Reality: German Pinschers are assertive and confident, which can be mistaken",
            "for aggression. With proper socialization and training, they are friendly and",
            "well-mannered dogs. However, they are naturally protective and will defend",
            "their family if they perceive a genuine threat.",
            "",
            "Myth: German Pinschers are hyperactive and cannot calm down.",
            "Reality: While German Pinschers are high-energy dogs, they are perfectly capable",
            "of being calm and relaxed in the house, provided they receive adequate exercise",
            "and mental stimulation. A well-exercised German Pinscher is a calm German",
            "Pinscher.",
            "",
            "Myth: German Pinschers are not good family dogs.",
            "Reality: German Pinschers can be excellent family dogs for the right family.",
            "They are loyal, protective, and playful. They do best with families who are",
            "active, experienced with dogs, and have children old enough to interact",
            "respectfully with the dog.",
            "",
            "Myth: German Pinschers are easy to train because they are smart.",
            "Reality: Intelligence does not automatically equal trainability. German",
            "Pinschers are smart, but they are also independent thinkers who will question",
            "the purpose of every command. Training a German Pinscher requires patience,",
            "consistency, and a good sense of humor.",
            "",
            "Myth: German Pinschers do not shed.",
            "Reality: German Pinschers shed moderately year-round and more heavily during",
            "seasonal changes. Their short hair may be less noticeable than the fur of",
            "longer-coated breeds, but it is there, and it will end up on your furniture",
            "and clothing.");

        AppendSection(sb, "CHAPTER 23: THE ULTIMATE ADVENTURE COMPANION",
            "",
            "As we reach the end of this comprehensive guide, it is worth reflecting on",
            "what makes the German Pinscher such a special breed. They are not the easiest",
            "dogs to own, nor are they the most popular. They are challenging, demanding,",
            "and sometimes exasperating. But for those who appreciate their unique qualities,",
            "there is simply no other breed that compares.",
            "",
            "The German Pinscher is a dog that will make you laugh every single day. Their",
            "antics, expressions, and sheer joie de vivre are infectious. They approach",
            "every day as a new adventure, every walk as an expedition, and every human",
            "interaction as an opportunity for connection.",
            "",
            "They are fiercely loyal, forming bonds with their families that are deep and",
            "unbreakable. A German Pinscher will follow you from room to room, lie at your",
            "feet while you work, and greet you at the door with unbridled joy every time",
            "you come home, whether you have been gone for eight hours or eight minutes.",
            "",
            "They are brave and protective, standing between their families and anything",
            "they perceive as a threat. Despite their moderate size, they have the heart",
            "of a lion and will not back down when they believe their loved ones are in",
            "danger.",
            "",
            "They are intelligent and curious, constantly learning and adapting to their",
            "environment. A German Pinscher is never truly 'trained.' They are always",
            "growing, always discovering, always finding new ways to surprise and delight",
            "their owners.",
            "",
            "And above all, they are adventurers. From the morning patrol to the midnight",
            "check, from the squirrel chase in the park to the beach expedition in summer,",
            "from the hiking trail to the camping trip, the German Pinscher approaches",
            "every experience with enthusiasm, curiosity, and an unshakeable belief that",
            "the next adventure is going to be the best one yet.",
            "",
            "If you are considering adding a German Pinscher to your family, prepare",
            "yourself for a journey unlike any other. It will be challenging at times,",
            "it will test your patience and your furniture, and it will fill your life",
            "with more love, laughter, and adventure than you ever thought possible.",
            "",
            "Welcome to the world of the German Pinscher. The adventure begins now.",
            "",
            "![dog](dog)");

        var lineCount = 0;
        foreach (var ch in sb.ToString())
            if (ch == '\n') lineCount++;
        lineCount++;

        while (lineCount < 3000)
        {
            sb.AppendLine();
            sb.AppendLine(GenerateFactLine(lineCount));
            lineCount += 2;
        }

        return sb.ToString();
    }

    private static string GenerateFactLine(int seed)
    {
        string[] facts =
        {
            "German Pinschers have a remarkable vertical leap, often clearing fences that appear too tall for their size.",
            "The breed's short coat makes them sensitive to extreme cold, requiring a warm jacket in winter months.",
            "A well-socialized German Pinscher can be a therapy dog, bringing joy to hospital patients and nursing home residents.",
            "German Pinschers are known for their 'Pinscher pounce' — a hunting technique where they leap and pin prey with their front paws.",
            "The breed's prey drive is so strong that even experienced owners are sometimes caught off guard by their speed.",
            "German Pinschers have excellent memory and can remember routes, people, and other dogs for years.",
            "The breed is sometimes called the 'middle Pinscher' because of its size between the Miniature and Doberman Pinschers.",
            "German Pinschers are naturally lean dogs, and even a few extra pounds can impact their health and agility.",
            "The breed's ancestors were depicted in artwork dating back to the 15th century in Germany.",
            "German Pinschers are known to 'talk' using a range of vocalizations including whines, grumbles, and yodels.",
            "The breed excels in barn hunt competitions, channeling their ancestral ratting instincts in a controlled setting.",
            "German Pinschers have a distinctive play bow that is more exaggerated than most breeds, nearly touching the ground.",
            "The breed's intelligence ranks among the top 50 of all dog breeds, according to canine cognition researchers.",
            "German Pinschers can run at speeds up to 25 miles per hour in short bursts during squirrel chases.",
            "The breed's coat color can darken or lighten slightly with age and sun exposure.",
            "German Pinschers are known for their 'helicopter tail' — spinning their tail in a complete circle when excited.",
            "The breed has a strong denning instinct and will seek out enclosed spaces like crates, closets, or under blankets.",
            "German Pinschers are surprisingly good at reading human emotions and will adjust their behavior accordingly.",
            "The breed's high metabolism means they need more calories per pound than many similar-sized breeds.",
            "German Pinschers are known to form especially strong bonds with one particular family member.",
            "The breed's alertness makes them natural candidates for search and rescue training.",
            "German Pinschers are one of the few breeds that can genuinely smile, pulling back their lips to show teeth in greeting.",
            "The breed's compact musculature gives them a strength-to-weight ratio that rivals much larger dogs.",
            "German Pinschers are known to 'counter surf' with remarkable stealth, snatching food without making a sound.",
            "The breed thrives in dog sports like agility, where their speed and quick turns earn them top scores.",
            "German Pinschers have a remarkable ability to sense approaching storms, often becoming restless hours before.",
            "The breed's ears are among the most expressive of any dog, conveying curiosity, alertness, and playfulness.",
            "German Pinschers are known to be escape artists, capable of finding and exploiting any weakness in a fence.",
            "The breed's sleek appearance has been compared to a sports car — elegant, fast, and built for performance.",
            "German Pinschers maintain their playful nature well into old age, still chasing toys at ten years and beyond.",
            "The breed is particularly sensitive to household chemicals and should be kept away from cleaning products.",
            "German Pinschers have an exceptional sense of smell and can detect treats hidden in the most unlikely places.",
            "The breed's loyalty is legendary — stories of German Pinschers waiting for their owners are common in breed lore.",
            "German Pinschers are known to arrange their toys in specific spots, suggesting a sense of order and territory.",
            "The breed can learn to respond to hand signals as readily as verbal commands, making them versatile working dogs.",
            "German Pinschers are surprisingly gentle with puppies and kittens, often taking on a nurturing role.",
            "The breed's short coat means they leave less dander than many breeds, though they are not hypoallergenic.",
            "German Pinschers are known for their 'zoomies' — sudden bursts of frantic running that defy all logic.",
            "The breed's intensity in play can sometimes be mistaken for aggression by unfamiliar onlookers.",
            "German Pinschers have a natural affinity for elevated surfaces and will climb onto tables, counters, and shelves.",
            "The breed is particularly responsive to clicker training, quickly associating the click with rewards.",
            "German Pinschers are known to 'guard' their food bowls, a behavior that should be addressed early in training.",
            "The breed's versatility means they can adapt to city apartments or country estates with equal ease.",
            "German Pinschers have a remarkable sense of time and will remind their owners of feeding and walking schedules.",
            "The breed's coat is naturally water-resistant, allowing them to dry quickly after a swim or bath.",
            "German Pinschers are known for their unwavering gaze, which they use to communicate needs and desires.",
            "The breed's combination of beauty, brains, and athleticism makes them a triple threat in the show ring.",
            "German Pinschers are one of the most photogenic breeds, with their sleek lines and expressive faces.",
            "The breed's history as vermin hunters means they have an instinctive dislike of rodents and similar animals.",
            "German Pinschers are known to be surprisingly affectionate, often seeking physical contact with their owners.",
        };

        return facts[seed % facts.Length];
    }

    private static void AppendSection(StringBuilder sb, string title, params string[] lines)
    {
        if (sb.Length > 0)
        {
            sb.AppendLine();
            sb.AppendLine();
        }
        sb.AppendLine(title);
        foreach (var line in lines)
            sb.AppendLine(line);
    }

    private static WriteableBitmap CreateSolidBitmap(Color color)
    {
        const int size = 32;
        var bmp = new WriteableBitmap(
            new PixelSize(size, size),
            new Vector(96, 96),
            PixelFormat.Bgra8888,
            AlphaFormat.Premul);

        using var buf = bmp.Lock();
        var pixels = new byte[size * size * 4];
        for (int i = 0; i < size * size; i++)
        {
            pixels[i * 4 + 0] = color.B;
            pixels[i * 4 + 1] = color.G;
            pixels[i * 4 + 2] = color.R;
            pixels[i * 4 + 3] = 255;
        }
        System.Runtime.InteropServices.Marshal.Copy(pixels, 0, buf.Address, pixels.Length);

        return bmp;
    }

    private void UpdateStatus()
    {
        var lineCount = string.IsNullOrEmpty(_markdownText) ? 0 : _markdownText.Split('\n').Length;
        StatusText = $"Lines: {lineCount}";
    }

    public event PropertyChangedEventHandler? PropertyChanged;

    protected void OnPropertyChanged([CallerMemberName] string? name = null) =>
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
}
